### ISSUE TITLE
Excessive Battery Fill Level Errors

### ISSUE THREAD

**Issue by sup3rm3ga** [itchannel/fordpass-ha#100]
Getting thousands of this one error. Any ideas?

`Logger: homeassistant
Source: custom_components/fordpass/sensor.py:205
Integration: FordPass (documentation, issues)
First occurred: May 19, 2021, 9:09:46 PM (1577 occurrences)
Last logged: 8:41:22 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 229, in device_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 205, in get_value
    "Battery Fill Level": self.coordinator.data["batteryFillLevel"][
TypeError: 'NoneType' object is not subscriptable`

**Comment by itchannel** [comment]
Do you have an electric car?

**Comment by Gruzzen** [comment]
I have an Electric Car and I receive errors on the following:

 File "/config/custom_components/fordpass/sensor.py", line 209, in get_value
    "Charger Power Type": self.coordinator.data["chargerPowertype"][

 File "/config/custom_components/fordpass/sensor.py", line 43, in get_value
    return round(self.coordinator.data[self.sensor]["fuelLevel"])

**Comment by itchannel** [comment]
Added some new guard against some errors when the vehicle doesn't support certain parameters. Let me know if you still get the errors in #104 as it's trial and error as I don't have an EV to test these bits.

**Comment by goofy7264** [comment]
1.17 release has fixed this issue for me.

**Comment by Gruzzen** [comment]
I still have the following errors for an EV.

`Logger: homeassistant.components.device_tracker
Source: custom_components/fordpass/sensor.py:52
Integration: Device tracker (documentation, issues)
First occurred: 9:49:19 PM (1 occurrences)
Last logged: 9:49:19 PM

fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 336, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/fordpass/sensor.py", line 361, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 52, in get_value
    return round(self.coordinator.data[self.sensor]["fuelLevel"])
TypeError: 'NoneType' object is not subscriptable
`

`Logger: homeassistant.components.sensor
Source: custom_components/fordpass/sensor.py:52
Integration: Sensor (documentation, issues)
First occurred: 9:49:18 PM (3 occurrences)
Last logged: 9:49:18 PM

Error adding entities for domain sensor with platform fordpass
Error while setting up fordpass platform for sensor
fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/fordpass/sensor.py", line 361, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 52, in get_value
    return round(self.coordinator.data[self.sensor]["fuelLevel"])
TypeError: 'NoneType' object is not subscriptable
`

`Logger: homeassistant.components.switch
Source: custom_components/fordpass/switch.py:21
Integration: Switch (documentation, issues)
First occurred: 9:49:18 PM (1 occurrences)
Last logged: 9:49:18 PM

Error while setting up fordpass platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fordpass/switch.py", line 21, in async_setup_entry
    if sw.coordinator.data["guardstatus"]["returnCode"] == 200:
  File "/usr/local/lib/python3.8/site-packages/dotted/collection.py", line 266, in __getitem__
    return self.store[key]
KeyError: 'guardstatus'
`

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:52
Integration: FordPass (documentation, issues)
First occurred: 9:54:19 PM (2 occurrences)
Last logged: 9:59:19 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/fordpass/sensor.py", line 361, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 52, in get_value
    return round(self.coordinator.data[self.sensor]["fuelLevel"])
TypeError: 'NoneType' object is not subscriptable
`

**Comment by itchannel** [comment]
@Gruzzen thanks for the output I'll get and fix those errors this week.

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
