### ISSUE TITLE
Log message: Error while setting up fordpass platform for switch

### ISSUE THREAD

**Issue by degrashopper** [itchannel/fordpass-ha#105]
Not sure if this is a new feature of your integration. after upgrading the integration from 1.15 to 1.17 i get at boot this message:

Error while setting up fordpass platform for switch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fordpass/switch.py", line 21, in async_setup_entry
    if sw.coordinator.data["guardstatus"]["returnCode"] == 200:
  File "/usr/local/lib/python3.8/site-packages/dotted/collection.py", line 266, in __getitem__
    return self.store[key]
KeyError: 'guardstatus'

**Comment by degrashopper** [comment]
during the day I got a lot of fordpass unavailable loggings. Moved back to 1.15. now everything is fine.

**Comment by itchannel** [comment]
#107 Should fix this error. There was an issue when checking to see if a car supports "Guard Mode" which resulted in an error.

**Comment by degrashopper** [comment]
So far so good. just updated to 1.19 and no error message at boot.
