### ISSUE TITLE
IgnitionSwitch entity unavailable

### ISSUE THREAD

**Issue by clartan2014** [itchannel/fordpass-ha#110]
I noticed that the IgnitionSwitch entity suddenly becomes unavailable. It's working fine before.

**Comment by itchannel** [comment]
Can you check your logs to see if you have any error messages. It's working fine for me on my prod and dev instances.

**Comment by clartan2014** [comment]
These are the ford-related logs i found.

1:04:54 PM – (ERROR) FordPass (custom integration) - message first occurred at 11:38:58 AM and shows up 18 times
Error parsing value: 'value_json' is undefined (value: on, template: {{value_json.state}})
Error adding entities for domain sensor with platform fordpass
11:33:54 AM – (ERROR) Sensor (custom integration) - message first occurred at 11:33:52 AM and shows up 3 times
Can't read mesh devices
2021-07-05 11:33:37 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fordpass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-05 11:33:52 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 409, in _async_write_ha_state
extra_state_attributes = self.device_state_attributes
File "/config/custom_components/fordpass/sensor.py", line 370, in device_state_attributes
return self.get_value("attribute")
File "/config/custom_components/fordpass/sensor.py", line 176, in get_value
self.coordinator.data["TPMS"]["leftFrontTirePressure"][
TypeError: 'NoneType' object is not subscriptable
2021-07-05 11:33:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fordpass platform for sensor
Traceback (most recent call last):

**Comment by clartan2014** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/fordpass/sensor.py:176
Integration: Sensor (documentation, issues)
First occurred: 11:33:52 AM (6 occurrences)
Last logged: 1:13:11 PM

Error adding entities for domain sensor with platform fordpass
Error while setting up fordpass platform for sensor
fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 409, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 370, in device_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 176, in get_value
    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
TypeError: 'NoneType' object is not subscriptable

**Comment by clartan2014** [comment]
i removed and readded the integration. it works now :) thanks!

**Comment by itchannel** [comment]
I'll have a look into that bug anyway as looks like some data was missing from your car status and the integration didn't fail nicely :)

**Comment by gilperme** [comment]
Same issue, I just reloaded - not removed - the integration and it worked right away. Thanks.
