### ISSUE TITLE
Fordpass Unavailable 

### ISSUE THREAD

**Issue by JVTEAM** [itchannel/fordpass-ha#133]
Starting the last few days Fordpass has been going back and forth to the unavailable status.  I'm on the current new version.  Haven't had a problem since I set it up a year ago.

**Comment by jrprinty** [comment]
I am seeing the same issue also. 

This error originated from a custom integration.

Logger: custom_components.fordpass
Source: custom_components/fordpass/__init__.py:167 
Integration: FordPass (documentation, issues) 
First occurred: 10:37:17 AM (1 occurrences) 
Last logged: 10:37:17 AM

Error communicating with FordPass for (VIN Number)

This is happening for both vehicle I have with FordPass.

**Comment by tunisiano187** [comment]
Same problem for me.

**Comment by bleeblak8** [comment]
I am also having the same problem.  I removed and added the integration again, still the same result.

**Comment by iannecj** [comment]
Same issue for me I think.  If I delete and then re-add it all works for a time.  

Here are my logs with debug on:





`2021-11-30 11:37:39 DEBUG (MainThread) [custom_components.fordpass.sensor] {'vin': 'XX', 'lockStatus': {'value': 'UNLOCKED', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'alarm': {'value': 'NOTSET', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'PrmtAlarmEvent': {'value': 'Null', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'odometer': {'value': 90832.0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'fuel': {'fuelLevel': 67.500216, 'distanceToEmpty': 617.9, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'gps': {'latitude': '28.7565183', 'longitude': '-81.3757800', 'gpsState': 'UNSHIFTED', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'remoteStart': {'remoteStartDuration': 0, 'remoteStartTime': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'remoteStartStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '11-30-2021 15:45:41'}, 'batteryStatusActual': {'value': 12, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'oil': {'oilLife': 'STATUS_GOOD', 'oilLifeActual': 50, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tirePressure': {'value': 'STATUS_GOOD', 'timestamp': '11-22-2019 17:43:28'}, 'authorization': 'AUTHORIZED', 'TPMS': {'tirePressureByLocation': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tirePressureSystemStatus': {'value': 'Systm_Activ_Composite_Stat', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'dualRearWheel': None, 'leftFrontTireStatus': None, 'leftFrontTirePressure': None, 'rightFrontTireStatus': None, 'rightFrontTirePressure': None, 'outerLeftRearTireStatus': None, 'outerLeftRearTirePressure': None, 'outerRightRearTireStatus': None, 'outerRightRearTirePressure': None, 'innerLeftRearTireStatus': None, 'innerLeftRearTirePressure': None, 'innerRightRearTireStatus': None, 'innerRightRearTirePressure': None, 'recommendedFrontTirePressure': None, 'recommendedRearTirePressure': None}, 'firmwareUpgInProgress': {'value': False, 'timestamp': '08-09-2020 02:03:02'}, 'deepSleepInProgress': {'value': False, 'timestamp': '09-18-2018 10:59:48'}, 'ccsSettings': {'timestamp': '10-07-2017 12:51:53', 'location': -1, 'vehicleConnectivity': -1, 'vehicleData': -1, 'drivingCharacteristics': -1, 'contacts': -1}, 'lastRefresh': '11-30-2021 15:45:41', 'lastModifiedDate': '11-30-2021 15:45:46', 'serverTime': '11-30-2021 16:37:10', 'batteryFillLevel': {'value': 50.0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'elVehDTE': None, 'hybridModeStatus': {'value': 'NullState', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargingStatus': {'value': 'NotReadyNullState', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'plugStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargeStartTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargeEndTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'preCondStatusDsply': None, 'chargerPowertype': {'value': 'NotCharging', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryPerfStatus': None, 'outandAbout': {'value': 'PwPckOffTqNotAvailable', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryChargeStatus': {'value': 'NoReportRequest', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'dcFastChargeData': None, 'windowPosition': {'driverWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'passWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'rearDriverWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'rearPassWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'doorStatus': {'rightRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'leftRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'driverDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'passengerDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'hoodDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'innerTailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'ignitionStatus': {'value': 'Off', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryTracLowChargeThreshold': None, 'battTracLoSocDDsply': None, 'dieselSystemStatus': None, 'guardstatus': {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': None}}
2021-11-30 11:37:39 DEBUG (MainThread) [custom_components.fordpass.sensor] {'vin': 'XX', 'lockStatus': {'value': 'UNLOCKED', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'alarm': {'value': 'NOTSET', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'PrmtAlarmEvent': {'value': 'Null', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'odometer': {'value': 90832.0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'fuel': {'fuelLevel': 67.500216, 'distanceToEmpty': 617.9, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'gps': {'latitude': '28.7565183', 'longitude': '-81.3757800', 'gpsState': 'UNSHIFTED', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'remoteStart': {'remoteStartDuration': 0, 'remoteStartTime': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'remoteStartStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'battery': {'batteryHealth': {'value': 'STATUS_GOOD', 'timestamp': '11-30-2021 15:45:41'}, 'batteryStatusActual': {'value': 12, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'oil': {'oilLife': 'STATUS_GOOD', 'oilLifeActual': 50, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tirePressure': {'value': 'STATUS_GOOD', 'timestamp': '11-22-2019 17:43:28'}, 'authorization': 'AUTHORIZED', 'TPMS': {'tirePressureByLocation': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tirePressureSystemStatus': {'value': 'Systm_Activ_Composite_Stat', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'dualRearWheel': None, 'leftFrontTireStatus': None, 'leftFrontTirePressure': None, 'rightFrontTireStatus': None, 'rightFrontTirePressure': None, 'outerLeftRearTireStatus': None, 'outerLeftRearTirePressure': None, 'outerRightRearTireStatus': None, 'outerRightRearTirePressure': None, 'innerLeftRearTireStatus': None, 'innerLeftRearTirePressure': None, 'innerRightRearTireStatus': None, 'innerRightRearTirePressure': None, 'recommendedFrontTirePressure': None, 'recommendedRearTirePressure': None}, 'firmwareUpgInProgress': {'value': False, 'timestamp': '08-09-2020 02:03:02'}, 'deepSleepInProgress': {'value': False, 'timestamp': '09-18-2018 10:59:48'}, 'ccsSettings': {'timestamp': '10-07-2017 12:51:53', 'location': -1, 'vehicleConnectivity': -1, 'vehicleData': -1, 'drivingCharacteristics': -1, 'contacts': -1}, 'lastRefresh': '11-30-2021 15:45:41', 'lastModifiedDate': '11-30-2021 15:45:46', 'serverTime': '11-30-2021 16:37:10', 'batteryFillLevel': {'value': 50.0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'elVehDTE': None, 'hybridModeStatus': {'value': 'NullState', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargingStatus': {'value': 'NotReadyNullState', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'plugStatus': {'value': 0, 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargeStartTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'chargeEndTime': {'value': '01-01-2010 00:00:00', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'preCondStatusDsply': None, 'chargerPowertype': {'value': 'NotCharging', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryPerfStatus': None, 'outandAbout': {'value': 'PwPckOffTqNotAvailable', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryChargeStatus': {'value': 'NoReportRequest', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'dcFastChargeData': None, 'windowPosition': {'driverWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'passWindowPosition': {'value': 'Fully_closed_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'rearDriverWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'rearPassWindowPos': {'value': 'Undefined_window_position', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'doorStatus': {'rightRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'leftRearDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'driverDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'passengerDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'hoodDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'tailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'innerTailgateDoor': {'value': 'Closed', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}}, 'ignitionStatus': {'value': 'Off', 'status': 'CURRENT', 'timestamp': '11-30-2021 15:45:45'}, 'batteryTracLowChargeThreshold': None, 'battTracLoSocDDsply': None, 'dieselSystemStatus': None, 'guardstatus': {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': None}}
2021-11-30 11:37:39 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': None}
2021-11-30 11:37:39 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-11-30 11:37:39 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 378, in device_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 179, in get_value
    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
TypeError: 'NoneType' object is not subscriptable
2021-11-30 11:37:39 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 378, in device_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 179, in get_value
    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
TypeError: 'NoneType' object is not subscriptable
2021-11-30 11:37:39 DEBUG (SyncWorker_1) [custom_components.fordpass.fordpass_new] Token is valid, continuing

2021-11-30 11:38:09 WARNING (MainThread) [custom_components.fordpass] 
2021-11-30 11:38:09 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for XX
2021-11-30 11:38:09 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for XX
2021-11-30 11:38:09 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 30.001 seconds (success: False)
2021-11-30 11:43:09 DEBUG (SyncWorker_7) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-11-30 11:43:09 DEBUG (SyncWorker_10) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-11-30 11:43:39 WARNING (MainThread) [custom_components.fordpass] 
2021-11-30 11:43:39 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for XX
2021-11-30 11:43:39 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 30.009 seconds (success: False)`

**Comment by xpac1985** [comment]
I have the same issues, and the culprit seems to be here:
https://github.com/itchannel/fordpass-ha/blob/02a2dee185937a64feaeed87a4afdcc69724eeeb/custom_components/fordpass/sensor.py#L179

I'd assume the response has changed, and the code logic can't deal with the new response. Ford seems to return no tire pressure data although it claims there is some...

**Comment by heyepic** [comment]
Mine just started working..

**Comment by bleeblak8** [comment]
Same here, just saw it was working.  What the heck is going on.

**Comment by JVTEAM** [comment]
> Mine just started working..

Mine is currently as well, but if you look at the HA history it has been off and on for me all day.

**Comment by iannecj** [comment]
Mine has some sensors populated, some not.

**Comment by itchannel** [comment]
It generally becomes unavailable when the integration cant communicate with the ford API. It looks like they were having problems in the last 24 hours hence the issue with the integration timing out. I'm hoping to have some time over the next week to check all the calls against the latest Fordpass app and update if needed but for now it should still work ok as long as the backend API is functional.

**Comment by iannecj** [comment]
In my case things dont come back at all.  I must delete and re-add from integrations page and then all sensors works for a time.  In the log above it mentions tire pressure and errors.

Here is what its says now:

2021-11-30 16:54:41 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-11-30 16:54:41 DEBUG (SyncWorker_5) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-11-30 16:54:42 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.116 seconds (success: True)
2021-11-30 16:54:42 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': None}
2021-11-30 16:54:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 378, in device_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 179, in get_value
    self.coordinator.data["TPMS"]["leftFrontTirePressure"][
TypeError: 'NoneType' object is not subscriptable
2021-11-30 16:55:04 DEBUG (SyncWorker_1) [custom_components.fordpass] Running Service
2021-11-30 16:55:04 DEBUG (SyncWorker_1) [custom_components.fordpass.fordpass_new] Token is valid, continuing

**Comment by itchannel** [comment]
@iannecj Yours looks like an issue where the tyre pressure doesn't always return data from the API. Does your car have tpms sensors?

Either way I'll add a check in the next release to handle a null "TPMS" array.

**Comment by iannecj** [comment]
Thanks.  It does have TPMS but one of the four batteries is out.  Not sure
if that could be the culprit.  Odd that on reload everything always works
for a time.

Thanks for this outstanding work.

Greatly appreciate what you have done here.

-C

**Comment by itchannel** [comment]
@iannecj New update should fix your TPMS issue. Just be aware of the breaking change which requires selecting your desired units in options and then restarting HA.

**Comment by iannecj** [comment]
Ok, I'll check it out. Thx!
