### ISSUE TITLE
custom_components/fordpass/sensor.py:53

### ISSUE THREAD

**Issue by Johnnyyr** [itchannel/fordpass-ha#136]
Logger: homeassistant
Source: custom_components/fordpass/sensor.py:53
Integration: FordPass (documentation, issues)
First occurred: 2. Dezember 2021, 20:22:55 (2224 occurrences)
Last logged: 22:33:54

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fordpass/sensor.py", line 346, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 53, in get_value
    if self.options[CONF_DISTANCE_UNIT] == "mi":
KeyError: 'distance_unit'

**Comment by itchannel** [comment]
This is related to the breaking change in #135 

You need to go to integrations and click "Options" on Fordpass and make sure the Units are set. Once you've done that click "Submit" and restart your HA.

**Comment by Johnnyyr** [comment]
I have the update already installt , last log at this morning.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:53
Integration: FordPass (documentation, issues)
First occurred: 13. Dezember 2021, 13:05:39 (216 occurrences)
Last logged: 07:14:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fordpass/sensor.py", line 362, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 53, in get_value
    if self.options[CONF_DISTANCE_UNIT] == "mi":
KeyError: 'distance_unit'
