### ISSUE TITLE
Fordpass not fully working

### ISSUE THREAD

**Issue by rkeyzer9** [itchannel/fordpass-ha#158]
I am using the fordpass integration for over a year but since a month i can't see the km (odometer) and the fuel anymore, in the fordpass app it is still working, someone has an idea?

**Comment by tobox** [comment]
Same for me with a Mustang Mach E electric vehicle. I don't get the SoC anymore - maybe it has something to do with the latest ELVDTE commit?

**Comment by itchannel** [comment]
Can you please check your logs and see if there is any errors related to this.

**Comment by cbennett6008** [comment]
I noticed this too, but also notice that if I look at the fordpass website, they don't display there anymore either.

**Comment by jofotoo** [comment]
I also have no odometer entity for several months. 
```
Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

```

1. Delted config, 
2. deleted HACS integration
3. ensured fordpass directory was gone
4.  re-installed
5. restarted HA (not reboot host)
6. re-installed

Here's my log from after setup
```
2022-12-07 10:32:18.397 INFO (MainThread) [homeassistant.setup] Setting up fordpass
2022-12-07 10:32:18.398 INFO (MainThread) [homeassistant.setup] Setup of domain fordpass took 0.0 seconds
2022-12-07 10:32:19.175 INFO (MainThread) [homeassistant.components.lock] Setting up lock.fordpass
2022-12-07 10:32:19.222 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.fordpass
2022-12-07 10:32:19.232 INFO (MainThread) [homeassistant.components.switch] Setting up switch.fordpass
2022-12-07 10:32:19.243 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.fordpass
2022-12-07 10:32:19.297 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new lock.fordpass entity: lock.fordpass_doorlock
2022-12-07 10:32:19.308 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.fordpass entity: switch.fordpass_ignition_switch
2022-12-07 10:32:19.360 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_fuel
2022-12-07 10:32:19.363 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_battery
2022-12-07 10:32:19.375 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_oil
2022-12-07 10:32:19.377 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_tirepressure
2022-12-07 10:32:19.405 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_gps
2022-12-07 10:32:19.407 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_alarm
2022-12-07 10:32:19.419 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_ignitionstatus
2022-12-07 10:32:19.421 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_doorstatus
2022-12-07 10:32:19.435 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_windowposition
2022-12-07 10:32:19.437 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_lastrefresh
2022-12-07 10:32:19.447 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_deepsleepinprogress
2022-12-07 10:32:19.451 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_firmwareupginprogress
2022-12-07 10:32:19.455 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_remotestartstatus
2022-12-07 10:32:19.458 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.fordpass entity: sensor.fordpass_messages
2022-12-07 10:32:19.461 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new device_tracker.fordpass entity: device_tracker.fordpass_tracker
2022-12-07 10:32:19.738 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/fordpass/sensor.py", line 401, in extra_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 218, in get_value
    tirepress[key] = round(float(value["value"]) * sval)
ValueError: could not convert string to float: ''
2022-12-07 10:32:19.835 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/fordpass/sensor.py", line 401, in extra_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 218, in get_value
    tirepress[key] = round(float(value["value"]) * sval)
ValueError: could not convert string to float: ''
2022-12-07 10:32:20.095 ERROR (MainThread) [homeassistant.components.sensor] fordpass: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 359, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 158, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/fordpass/sensor.py", line 401, in extra_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 218, in get_value
    tirepress[key] = round(float(value["value"]) * sval)
ValueError: could not convert string to float: ''
```

**Comment by itchannel** [comment]
@jofotoo Give 1.40 a go for me. Looks like even though I do a null check for tire pressure values your car is reporting back a value of ""

**Comment by jofotoo** [comment]
> @jofotoo Give 1.40 a go for me. Looks like even though I do a null check for tire pressure values your car is reporting back a value of ""

Sadly it didn't help. log looks about the same. I deleted the integration and re-added it. Then realized maybe i need to refresh the browser but it didn't help. i restarted HA after the update install.

**Comment by jofotoo** [comment]
I wanted to clarify that I don't even have an odometer entity, though I used to. FordPass _does_ show an odometer in my account

**Comment by giulianonm** [comment]
Same problem here. I always had the odometer hass sensor working well, but in a month ago, "unavaiable" was displayed as its value. So I deleted the entity, hoping it would return at any future updates, but I can't have it back anymore. Far from being a hass technical expert, now I'm getting lost in how to reestablish this entity.

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
