### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Johnnyyr** [itchannel/fordpass-ha#162]
Logger: homeassistant
Source: custom_components/fordpass/sensor.py:180
Integration: FordPass ([documentation](https://github.com/itchannel/fordpass-ha), [issues](https://github.com/itchannel/fordpass-ha/issues))
First occurred: 13:51:03 (2 occurrences)
Last logged: 13:56:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/fordpass/sensor.py", line 384, in extra_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 180, in get_value
    if self.options[CONF_DISTANCE_UNIT] == "mi":
KeyError: 'distance_unit'

**Comment by nwykoff** [comment]
Similar issue here:
Logger: homeassistant
Source: util/speed.py:45
First occurred: February 5, 2022, 10:18:15 PM (3 occurrences)
Last logged: 12:58:15 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 237, in state_attributes
    self.hass.config.units.wind_speed(wind_speed, unit),
  File "/usr/src/homeassistant/homeassistant/util/unit_system.py", line 167, in wind_speed
    return speed_util.convert(wind_speed, from_unit, self.wind_speed_unit)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/util/speed.py", line 45, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(unit_1, SPEED))
ValueError: mi/h is not a recognized speed unit.

**Comment by itchannel** [comment]
Is this a new install or an upgrade from previous before I made the change in 1.13? Can you just try going to the fordpass options screen and hitting save/submit to update the values.

**Comment by Bert-R** [comment]
I occasionally have such errors too, with slightly different line numbers:

```
(MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 569, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 542, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/fordpass/sensor.py", line 376, in state
return self.get_value("state")
File "/config/custom_components/fordpass/sensor.py", line 72, in get_value
return self.coordinator.data[self.sensor]["value"]
TypeError: 'NoneType' object is not subscriptable
```

With 'occasionally', I mean 11 times this year.

**Comment by itchannel** [comment]
It looks like certain sensor values are blank when receiving data back from your car. Can you please add the following to HA to provide more indepth logging so I can see what data is missing:

```
logger:
  logs:
    custom_components.fordpass: debug
```

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
