### ISSUE TITLE
Unexpected error while authorizing

### ISSUE THREAD

**Issue by jeffkindred** [itchannel/fordpass-ha#183]
I noticed that the integration had stopped functioning as expected a couple of days ago. I was able to reload it and get it working for another day or so. It went unavailable again, so I deleted and reinstalled the integration via HACS and was met with an "Unexpected error" while authorizing. I tried a different password and got an "Invalid credentials" error. I logged into the FordPass app on my iPhone and had to agree to the EULA/ToS which I figured was what was blocking the authorization in HA but I received the same error when attempting auth in HA again...

I updated to the latest beta branch (1.32Beta) and tried again and received the same unexpected error.

I have seen in other threads that I should enable more verbose logging to do better debugging and have done so, but the error in the logs never gets more verbose than this:

```
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fordpass/config_flow.py", line 48, in validate_input
    result3 = await hass.async_add_executor_job(vehicle.vehicles)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fordpass/fordpass_new.py", line 265, in vehicles
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://services.cx.ford.com/api/dashboard/v1/users/vehicles
```

The integration was working really well since I initially installed it a while ago. I did recently add a new firewall to my network but mostly ruled that out as the culprit because the timelines don't line up... though it's not completely ruled out ;)

Anyway, all help with this is appreciated!

Edit: I checked my firewall/ad blocker logs (because when I typed it out above, it was the first time I correlated the two events) and the URL above was not blocked explicitly. I found that another URL was being blocked so I whitelisted it but its likely just for Ford collecting analytics from their app. I attempted authorizing again via HA and received the same unexpected error again.

**Comment by buzzbronski** [comment]
Getting the same error. When going to that URL mentioned in the logs I also receive this error: { "statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }

Looks like we'll have to wait for the dev to implement a fix.

**Comment by ThePitaGyros** [comment]
The integration worked flawlessly 22 hours ago (June 20, 19:06 GMT), and then suddenly stopped working.
Now I get the following errors...

```
022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass] username
2022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass] password
2022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass] vin
2022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass] region
2022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass] UK&Europe
2022-06-21 19:13:05 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/fordpass_token.txt
2022-06-21 19:13:05 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2022-06-21 19:13:05 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-06-21 19:13:06 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] 401 with status request: start token refresh
2022-06-21 19:13:06 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2022-06-21 19:13:06 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2022-06-21 19:13:06 WARNING (MainThread) [custom_components.fordpass] local variable 'result' referenced before assignment
2022-06-21 19:13:06 WARNING (MainThread) [custom_components.fordpass] Error communicating with FordPass for XYZ
2022-06-21 19:13:06 ERROR (MainThread) [custom_components.fordpass] Error fetching fordpass data: Error communicating with FordPass for XYZ
```

I tried to reauthorize and got the same "unexpected error" with the following log entries...

```
 File "/config/custom_components/fordpass/fordpass_new.py", line 265, in vehicles
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://services.cx.ford.com/api/dashboard/v1/users/vehicles
```

which looks like the same error that @jeffkindred mentioned before.

If I can help with further tests / info - please let me know.
Love the integration!

**Comment by ThePitaGyros** [comment]
I was not on the beta cannel - always a mistake ;-)
Just tried the 1.32beta version of the integration - with this version, things seem to work again.

@jeffkindred Try the beta - maybe the fixes things for you too.

**Comment by jeffkindred** [comment]
I already tried 1.32Beta as part of my troubleshooting and had the same issue

**Comment by jeffkindred** [comment]
I just tried the beta again, and it worked this time... not sure what happened the first time I tried it, maybe I forgot to restart HA or something. 

Thanks for the great integration and keeping up on the maintenance :)
