### ISSUE TITLE
Unexpected exception on installation

### ISSUE THREAD

**Issue by Tuschz** [itchannel/fordpass-ha#184]
So i had this integration working, and one day it just stopped working.

I reset my PW for Fordpass and removed the integration.
I redownloaded from HACS and restarted HA.

When trying to set it up again i had below error

```
This error originated from a custom integration.

Logger: custom_components.fordpass.config_flow
Source: custom_components/fordpass/fordpass_new.py:265
Integration: FordPass (documentation, issues)
First occurred: 06:40:37 (1 occurrences)
Last logged: 06:40:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fordpass/config_flow.py", line 48, in validate_input
    result3 = await hass.async_add_executor_job(vehicle.vehicles)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fordpass/fordpass_new.py", line 265, in vehicles
    r.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://services.cx.ford.com/api/dashboard/v1/users/vehicles
```

**Comment by Tuschz** [comment]
Sorry, didn't see the other issue with same error
