### ISSUE TITLE
MutableSequence not available in home assistant July beta core-2022.7.0b0

### ISSUE THREAD

**Issue by scooper1** [itchannel/fordpass-ha#190]
getting fatal integration load error on latest home assistant beta core-2022.7.0b0

`2022-06-30 10:22:02 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.fordpass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/fordpass/__init__.py", line 8, in <module>
    from dotted.collection import DottedDict
  File "/usr/local/lib/python3.10/site-packages/dotted/collection.py", line 154, in <module>
    class DottedList(DottedCollection, collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'
2022-06-30 10:22:02 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration fordpass: Unable to import component: Exception importing custom_components.fordpass`

**Comment by itchannel** [comment]
@scooper1 Thanks for the heads up. I've removed the affected library from the next version and will push once I've finished testing 👍

**Comment by scooper1** [comment]
confirm fixed in beta2  thanks
