### ISSUE TITLE
Broken on Home Assistant 2022.7.0

### ISSUE THREAD

**Issue by dennisbrouwer91** [itchannel/fordpass-ha#194]
On the new version of Home Assistant 2022.7.0 the integration doesn’t start anymore :

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/fordpass/__init__.py", line 8, in <module>
    from dotted.collection import DottedDict
  File "/usr/local/lib/python3.10/site-packages/dotted/collection.py", line 154, in <module>
    class DottedList(DottedCollection, collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence' `

**Comment by itchannel** [comment]
@dennisbrouwer91 have you updated to the latest fordpass version in Hacs 1.35? As this was fixed in that release 👍

**Comment by dennisbrouwer91** [comment]
Thanks for the quick reply! That indeed fixed it. Sorry, my bad! Verstuurd vanaf mijn iPhoneOp 8 jul. 2022 om 01:21 heeft itchannel ***@***.***> het volgende geschreven:﻿
@dennisbrouwer91 have you updated to the latest fordpass version in Hacs 1.35? As this was fixed in that release 👍
