### ISSUE TITLE
inconsistent functioning

### ISSUE THREAD

**Issue by cjramseyer** [itchannel/fordpass-ha#199]
Setup Fordpass integration with 2017 F-150 Platinum.
Setup completes successfully, and all 17 added sensors function (doorlock, window position, etc.)
Remote start functionality works as expected.

Occassionally, 15 of the sensor will become "unavailable", but then refresh and are available again.

These error below are showing in the log:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:211
Integration: Fordpass (documentation, issues)
First occurred: July 21, 2022 at 5:58:36 PM (185 occurrences)
Last logged: 9:21:22 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/fordpass/sensor.py", line 386, in extra_state_attributes
    return self.get_value("attribute")
  File "/config/custom_components/fordpass/sensor.py", line 211, in get_value
    tirepress[key] = round(float(value["value"]) * sval)
ValueError: could not convert string to float: ''

Are the unavailable sensors because of this?

**Comment by itchannel** [comment]
This is due to the API sometimes not responding so the integration marks the sensors as unavailable until it can refresh the data from the Fordpass API again. Unfortunately with this being an unofficial integration and not having API developer access there's not much that can be done.

**Comment by itchannel** [comment]
Closing as no reply's in a year
