### ISSUE TITLE
South Africa

### ISSUE THREAD

**Issue by greg10810** [itchannel/fordpass-ha#247]
We have a large community of Ford owners here, would be great to have this integration available.

**Comment by cyrenaud** [comment]
I would love to have this integration available for South Africa too. I'm sure there are plenty of us that would be willing to assist (with guidance) if required.

**Comment by itchannel** [comment]
Have you tried selecting the other regions and trying to see if it works? I'm guessing the south African Fordpass app is the same as the US one?

In order to make it fully compatible I would need to guide someone through using Burp (Proxy) to intercept the Fordpass application on their device so I can get the relevant region code which I'm happy to do if someone wants to give it a try. Just need some Fordpass details first e.g. 
- Screenshot of data displayed in Fordpass app
- Version of Fordpass avaliable on your local app store

**Comment by greg10810** [comment]
Thanks for getting back to me,

I have tried each of the 3 regions using both my cell number and email
address as ID, unfortunately none of them work, I have attached the
"invalid authentication" error that I get.

Appreciate you looking into this, more than happy to gather Burp data, just
give me a quick rundown of how to do this and what info you need from me.

I have attached screenshots of the available data from the app. App is
version: 4.24.3

I am using an android phone.

Cheers,
Greg

**Comment by itchannel** [comment]
I don't see any of the attachments you mentioned. Can you do me a favour and enabled debug logging for fordpass in your HA configuration and then send me the relevant logs when you try logging in so I can see exactly the error you are getting back. 

```
logger:
  default: warning
  logs:
    custom_components.fordpass: debug
```

If you can do the above first before going down the proxy route as it's not the easiest to explain and can be a little fiddly if you've never used a proxy before.

**Comment by jonathankretzmer** [comment]
I'm quite interested in getting this integration working for South Africa as well.

Here are my debug logs:

`2023-04-01 14:04:09.765 DEBUG (MainThread) [custom_components.fordpass.config_flow] UK&Europe
2023-04-01 14:04:09.765 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/(REMOVED)_fordpass_token.txt
2023-04-01 14:04:09.765 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] New System
2023-04-01 14:06:13.410 DEBUG (MainThread) [custom_components.fordpass.config_flow] North America & Canada
2023-04-01 14:06:13.411 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/(REMOVED)_fordpass_token.txt
2023-04-01 14:06:13.412 DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] New System
2023-04-01 14:06:52.134 DEBUG (MainThread) [custom_components.fordpass.config_flow] Australia
2023-04-01 14:06:52.135 DEBUG (MainThread) [custom_components.fordpass.fordpass_new] /config/custom_components/fordpass/(REMOVED)_fordpass_token.txt
2023-04-01 14:06:52.135 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] New System`

Tried getting the Burp proxy working, you're right it is quite fiddly. Started going down the road of loading the CA certificate onto the Android phone, but then ran into instructions for using ADB, etc. Is this the right direction?

**Comment by theunidj** [comment]
Keen to see this working for South Africa too. Let me know if I can help with logs too.

**Comment by greg10810** [comment]
@itchannel would be great if we could revisit this, seems that there is some interest in this working in SA. 

If you still need logs, happy to send

**Comment by theunidj** [comment]
> @greg10810 Out of interest does it let you login here: https://sso.ci.ford.com
> 
> That's what the API authenticates against. If that works for you then we can troubleshoot from there.

i get "We’re sorry, an error has occurred." when trying to reset my password on that link. I don't think i ever created an account.

**Comment by itchannel** [comment]
It's the same account you use to login to the fordpass application on your phone. That's just the web interface for the fordpass backend.

**Comment by theunidj** [comment]
the ford pass app requests a mobile number whilst the link above (when accessed on PC) requests an email. when I access that link on mobile it requests a mobile number and I am able to log in.

**Comment by itchannel** [comment]
oh interesting. For most people it asks for an email not a phone number. 

So for you does it ask for phone number and password?

Any chance you could send me a screenshot of the login you see?

**Comment by theunidj** [comment]
sign in on mobile- https://i.imgur.com/Z1zbMx5.jpg
sign in on desktop - https://i.imgur.com/SoI0w9G.png
ford pass sign in on mobile - https://i.imgur.com/mSULtW7.jpg

**Comment by theunidj** [comment]
if i put in my email or mobile number from desktop it doesn't log in.

**Comment by theunidj** [comment]
sooo, after looking into the fordpass app on my mobile under the accounts section, i noted that they don't keep the 0 in front of my mobile number. when removing the 0 from the username field and just using the rest of my mobile number, I've managed to add the intergation to HA selecting the Europe and Uk option. i've managed to add a HA integration using UK&Europe and dropping the 0 from front of my mobile number.

**Comment by itchannel** [comment]
@theunidj Nice! If another couple of people can also confirm that works for them. Then I can make a couple of changes to the workflow for anyone required to use a mobile number rather than email.

**Comment by greg10810** [comment]
> @greg10810 Out of interest does it let you login here: https://sso.ci.ford.com
> 
> That's what the API authenticates against. If that works for you then we can troubleshoot from there.

I was able to submit my phone number (without the 0) and password, but just get a blank screen

**Comment by greg10810** [comment]
> @theunidj Nice! If another couple of people can also confirm that works for them. Then I can make a couple of changes to the workflow for anyone required to use a mobile number rather than email.

![Screenshot 2023-08-24 at 17 42 02](https://github.com/itchannel/fordpass-ha/assets/76251159/965fc92c-ad8b-47a8-8b54-25378323e6e1)

Unfortunately I am unable to add FordPass integration, as per the screenshot.

**Comment by greg10810** [comment]
> @theunidj Nice! If another couple of people can also confirm that works for them. Then I can make a couple of changes to the workflow for anyone required to use a mobile number rather than email.

![Screenshot 2023-08-24 at 17 42 02](https://github.com/itchannel/fordpass-ha/assets/76251159/965fc92c-ad8b-47a8-8b54-25378323e6e1)


Unfortionately I am unable to add FordPass integration, as per the screenshot.

**Comment by itchannel** [comment]
@greg10810 What version of the integration are you running? and can you turn on debug logging and check your logs for any errors. 

Also try signing into the below website and tell me if it works for you:

https://www.ford.co.za/support/vehicle-dashboard

**Comment by greg10810** [comment]
@itchannel currently running 1.49, I can log into the site and view my vehicle. 

I am currently updating the vehicle firmware to the latest version - will revert with debug logs

**Comment by greg10810** [comment]
This error originated from a custom integration.

Logger: custom_components.fordpass.config_flow
Source: custom_components/fordpass/fordpass_new.py:370
Integration: FordPass (documentation, issues)
First occurred: 09:31:08 (1 occurrences)
Last logged: 09:31:08

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fordpass/config_flow.py", line 83, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/config_flow.py", line 62, in validate_input
    vehicles = await(hass.async_add_executor_job(vehicle.vehicles))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 370, in vehicles
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.mps.ford.com/api/expdashboard/v1/details/

**Comment by greg10810** [comment]
@itchannel let me know if you need more info

**Comment by SquidBytes** [comment]
#417 #400
