### ISSUE TITLE
Error when no indicator array exists

### ISSUE THREAD

**Issue by itchannel** [itchannel/fordpass-ha#340]
Ford Focus 21 Model UK Diesel Manual

Im running latest 1.54 Release 2

I added the utility meters and they were working until the API change, They are looking for the speed_odometer but that doesnt seem to exist any more. Does anyone know where the mileage is now please with fordpass_odometer being unavailable?

Is this what I should expect or is the app not responding as you would expect as I have 2 sensors not pulling anything as you can see fordpass_dieselSystemStatus and fordpass_exhaustFluidLevel

image
image

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:44 (1 occurrences)
Last logged: 12 October 2023 at 21:06:44

Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
return self.get_value("attribute")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
if "dieselExhaustOverTemp" in self.data["indicators"]:
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:44 (1 occurrences)
Last logged: 12 October 2023 at 21:06:44

Error while setting up fordpass platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
return self.get_value("attribute")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
if "dieselExhaustOverTemp" in self.data["indicators"]:
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
 Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: 12 October 2023 at 21:06:47 (1 occurrences)
Last logged: 12 October 2023 at 21:06:47

fordpass: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
await self.async_update()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 507, in async_update
await self.coordinator.async_request_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
await self._debounced_refresh.async_call()
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
await task
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
await self._async_refresh(log_failures=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
return self.get_value("attribute")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
if "dieselExhaustOverTemp" in self.data["indicators"]:
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/fordpass/sensor.py:484
Integration: FordPass (documentation, issues)
First occurred: 12 October 2023 at 21:21:53 (40 occurrences)
Last logged: 07:10:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 527, in extra_state_attributes
return self.get_value("attribute")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fordpass/sensor.py", line 484, in get_value
if "dieselExhaustOverTemp" in self.data["indicators"]:
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'indicators'
`

Hope this helps

**Comment by itchannel** [comment]
Added to 1.56 release
