### ISSUE TITLE
Keyerror: 'batteryStateOfCharge' in Log

### ISSUE THREAD

**Issue by jlabataille** [itchannel/fordpass-ha#377]
Data returns unhandled key error from "batteryStateOfCharge".  Unhandled error.  This error occurs for every set or returned data.  I have tried to clear error by triggering a poll API, reload, and refresh data, but this error always occurs.  I also tried deleting and reinstalling the integration, but same problem.  

Could exception capture logic be added so the remaining dataset is returned properly to HA?

Error log below:

```
Logger: homeassistant
Source: custom_components/fordpass/sensor.py:108
Integration: Fordpass (documentation, issues)
First occurred: 9:25:44 AM (56 occurrences)
Last logged: 11:15:50 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 574, in state
    return self.get_value("state")
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 108, in get_value
    return round(self.data["batteryStateOfCharge"]["value"])
                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'batteryStateOfCharge'

```

**Comment by itchannel** [comment]
Looks like your vehicle doesn't support the state of charge of the battery. (Will fix in next release)

What is the model and age of the vehicle?

**Comment by itchannel** [comment]
Please try the 1.58 Release this issue should be resolved.

**Comment by jlabataille** [comment]
Thank you.  This particular issue appears to be corrected in the latest version.
