### ISSUE TITLE
fordpass_elVehCharging on a ford F150 (Raptor not Lightning)

### ISSUE THREAD

**Issue by theOrakle** [itchannel/fordpass-ha#412]
I just want to document this - all else is fully functional.

It looks like it tried to create an unavailable entity sensor.fordpass_elVehCharging

Relevant Error:
```
2023-10-26 19:55:35.001 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fordpass
Traceback (most recent call last):
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 189, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.raptor_fuel cannot be added a second time to an entity platform
2023-10-26 19:55:35.030 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fordpass platform for sensor
Traceback (most recent call last):
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 189, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.raptor_fuel cannot be added a second time to an entity platform
2023-10-26 19:55:47.257 ERROR (MainThread) [custom_components.fordpass] Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.fordpass.FordPassDataUpdateCoordinator object at 0x7f763721fbd0>>
Traceback (most recent call last):
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homeassistant/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homeassistant/config/custom_components/fordpass/sensor.py", line 450, in extra_state_attributes
    return self.get_value("attribute")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homeassistant/config/custom_components/fordpass/sensor.py", line 324, in get_value
    if ch_volt != 0 and ch_amps != 0:
       ^^^^^^^
UnboundLocalError: cannot access local variable 'ch_volt' where it is not associated with a value
```

**Comment by SquidBytes** [comment]
Probably related to #402 
It is being corrected
It's also my fault. Apologies for the difficulties

**Comment by theOrakle** [comment]
no needed apologies - happy to use your code.   Not sure why HACS wasn't alerting me of updates.  I'll update...
