### ISSUE TITLE
Sensor available/unavailable cycle on v1.70

### ISSUE THREAD

**Issue by thewolfman56** [itchannel/fordpass-ha#530]
I have an automation that lets me know when my wife's expedition goes below a certain threshold of miles left in the tank.  This automation recently started firing every hour.  I checked the sensor history for the vehicle and it appears that there is now a cycle that the sensor is available for 30 minutes, then unavailable for 30 minutes.

Here is the history of the door sensor for example.

![image](https://github.com/user-attachments/assets/13ab1905-69e9-4268-b504-365081802767)

**Comment by hroling** [comment]
I have the same issue with my Ford EcoSport. (Installed 1.70 Yesterday)

![image](https://github.com/user-attachments/assets/4438f4bf-d627-4b69-9386-6b0ca47c0a48)

**Comment by hroling** [comment]
It looks that if you refresh every 15 minutens, this issue is solved. I created an automation like this one.

```
alias: "Auto: Ford EcoSport refresh"
description: ""
trigger:
  - platform: time_pattern
    minutes: /15
condition: []
action:
  - action: fordpass.refresh_status
    data: {}
mode: single 
```

**Comment by thewolfman56** [comment]
> It looks that if you refresh every 15 minutens, this issue is solved. I created an automation like this one.
> 
Thanks.  I'll try that.  I used to have a similar automation for my MyDolphin pool robot cleaner that would reload the integration whenever the AWS broker connection became unavailable.

**Comment by JackKlaasing** [comment]
> It looks that if you refresh every 15 minutens, this issue is solved. I created an automation like this one.
> 
> ```
> alias: "Auto: Ford EcoSport refresh"
> description: ""
> trigger:
>   - platform: time_pattern
>     minutes: /15
> condition: []
> action:
>   - action: fordpass.refresh_status
>     data: {}
> mode: single 
> ```

And at the setup of the fordpass, the standard api refresh polling rate is 900s
What do you enter there, so you will not get banned?

**Comment by hroling** [comment]
> > It looks that if you refresh every 15 minutens, this issue is solved. I created an automation like this one.
> > ```
> > alias: "Auto: Ford EcoSport refresh"
> > description: ""
> > trigger:
> >   - platform: time_pattern
> >     minutes: /15
> > condition: []
> > action:
> >   - action: fordpass.refresh_status
> >     data: {}
> > mode: single 
> > ```
> 
> And at the setup of the fordpass, the standard api refresh polling rate is 900s What do you enter there, so you will not get banned?

It solved the issue for a week but it is back....

![image](https://github.com/user-attachments/assets/6af01572-a233-4816-910a-53038f3f17e0)

**Comment by Milkysunshine** [comment]
Same issue here.

Here's the log entry:

First occurred: October 10, 2024 at 12:10:54 PM (58 occurrences)
Last logged: 9:59:27 AM

Error fetching fordpass data: Error communicating with FordPass for *redacted vin*

**Comment by Milkysunshine** [comment]
I was able to get around this bug.

I reconfigured the FordPass integration to refresh every 180000000 seconds... (50,000) hours.

I already had this script I used on occasion if I wanted a manual update:

```
alias: Update FordPass
sequence:
  - action: fordpass.refresh_status
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: fordpass.poll_api
    metadata: {}
    data: {}
description: ""
```
I am guessing it would work with a shorter than 1 minute delay, but I have not tested it. This works reliably for me at 60 seconds.

So I created an automation that calls the script every 20 minutes: ( I kept it 20 to not overload the api, to avoid bans, and I personally don't need the information updated any more frequently than that. )

```
alias: "Time: Update FordPass every 20 minutes"
description: ""
triggers:
  - trigger: time_pattern
    minutes: /20
conditions: []
actions:
  - action: script.update_fordpass
    metadata: {}
    data: {}
mode: single

```

I have not had a single failed update since doing this. 


![Screenshot 2024-10-28 084814](https://github.com/user-attachments/assets/c5c69866-3206-4576-897f-d5f9146342d1)


I'm not sure why the built in polling doesn't work reliably, but this does... I didn't look into the source code.

I hope this helps others with the problem, or helps pinpoint the issue.

**Comment by hroling** [comment]
Tried. Thanks for the tip

It is not working for me. 30 min block vs 15 min block.

**Comment by Milkysunshine** [comment]
Did you reconfigure the integration and set the refresh time to a stupid hugh number?

**Comment by hroling** [comment]
> Did you reconfigure the integration and set the refresh time to a stupid hugh number?

Forgotten.... Set it now to 180000000.

Thanks and wait for the data.

**Comment by thewolfman56** [comment]
> I was able to get around this bug.
> 
> I'm not sure why the built in polling doesn't work reliably, but this does... I didn't look into the source code.
> 
> I hope this helps others with the problem, or helps pinpoint the issue.

@Milkysunshine Thanks for sharing this.  I was still getting only blocks of updates (seemed like every other day), but I'll try this script and automation.  I only disabled my other refresh automation for now in case i have to revert to it, but hoping your combination works.

**Comment by gmbrown21** [comment]
>  I was still getting only blocks of updates (seemed like every other day), but I'll try this script and automation. I only disabled my other refresh automation for now in case i have to revert to it, but hoping your combination works.

I noticed that I was only getting updates when my car was "active"--like if the car was connected to the EVSE and actively charging, or if I was driving or had just parked. Over night, there would be no updates. My assumption was that the car perhaps went into "dormant" mode when it had nothing new to report that was relevant to the entities created by the integration, and maybe that the integration similarly did not actively refresh the status itself if it discovered nothing new from the API, unless I were to do something like call the refresh service manually or lock or unlock the doors with the integration. That seemed reasonable to me, though I kind of get the idea that that isn't necessarily the expected behavior.

**Comment by hroling** [comment]
No blocks with unavailable anymore but also no new information. Still the data of Yesterday. 

Searching for the issues :) :)

**Comment by thewolfman56** [comment]
The new automation seems to be working better than what I had before.  The vehicle has been idle for 6 hours, but this is the outside temp sensor (best one I could think of that would be changing while sitting).

![image](https://github.com/user-attachments/assets/a2698460-2df2-4e6b-b8a4-65abe0d71bcb)

**Comment by Milkysunshine** [comment]
It definitely isn't a cure... more of a band-aid to prevent the stretches of unavailable data.

I say that because the home assistant log still shows errors.

```
Logger: homeassistant.components.script.update_fordpass
Source: helpers/script.py:525
integration: Script (documentation, issues)
First occurred: October 27, 2024 at 12:35:53 PM (93 occurrences)
Last logged: 9:45:53 AM

Update FordPass: Error executing script. Unexpected error for call_service at pos 1: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/__init__.py", line 86, in async_refresh_status_service
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/__init__.py", line 157, in refresh_status
    status = coordinator.vehicle.request_update(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 590, in request_update
    self.__acquire_token()
  File "/config/custom_components/fordpass/fordpass_new.py", line 331, in __acquire_token
    result = self.refresh_token_func(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/fordpass_new.py", line 262, in refresh_token_func
    response = session.post(
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

The 'Remote end closed connection without response' persisted occasionally even when I set the "refresh" rate to 30 minutes. 

I just changed it to 45 minutes in order to see if it is some sort or rate limit being imposed by the server.

**Comment by thewolfman56** [comment]
> It definitely isn't a cure... more of a band-aid to prevent the stretches of unavailable data.
> 
> I say that because the home assistant log still shows errors.

I don't think anyone thinks that needing to add an automation to refresh the integration is a cure, but it makes the integration work better for now while the developer has a chance to figure it our in the long run.  A similar situation happened with my pool robot custom integration.  I had to add an automation that would reload the integration whenever it was disconnected.  Luckily, the developers of the integration added a sensor to monitor the connection to AWS, so it was easy to implement the automation while they worked on a solution.  They eventually figured it out, but it took them a while.

**Comment by hroling** [comment]
I looks like it is working after the restart of Home Assistent. We know more tomorrow. :) 
![image](https://github.com/user-attachments/assets/88970689-bd12-447d-9e29-39d6ec84bb39)

**Comment by gmbrown21** [comment]
> > It definitely isn't a cure... more of a band-aid to prevent the stretches of unavailable data.
> 
> > 
> 
> > I say that because the home assistant log still shows errors.
> 
> 
> 
> I don't think anyone thinks that needing to add an automation to refresh the integration is a cure, but it makes the integration work better for now while the developer has a chance to figure it our in the long run. 

Your automation does work well, except, at least with my car (Mustang Mach-E), it seems to lead to a slow, but steady, drain of the 12V battery. Shutting off the automation overnight also seems to have stopped the drain. I'm either going to have to have it run less often than every 20 minutes or run it manually or find another way for it to run often enough to be useful without draining the battery.

**Comment by Milkysunshine** [comment]
> Your automation does work well, except, at least with my car (Mustang Mach-E), it seems to lead to a slow, but steady, drain of the 12V battery. Shutting off the automation overnight also seems to have stopped the drain. I'm either going to have to have it run less often than every 20 minutes or run it manually or find another way for it to run often enough to be useful without draining the battery.

You could add a conditional check to the automation that tells it not to update between x and y times.

**Comment by zdietzen** [comment]
This has helped me a lot so far so I appreciate everyone's input into this! I notice I get Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) sometimes when I run the script to refresh the Fordpass data. 

It also happens sometimes if I attempt to lock/unlock or remote start from HA. I will get Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) then I can hit the button/action again and it will work the second time.

I am trying a little workaround by running the FordPass refresh script which runs twice, and im also running the FordPass refresh script just before I run my car start automation. I'm hoping this will get things working. 

Here is my yaml for starting my car in the morning-

Here is my FordPass Update script that calls the refresh and poll twice in case the error happens the first time-

```
alias: Update FordPass
sequence:
  - repeat:
      count: 2  # Try up to 2 times (first attempt + retry)
      sequence:
        - action: fordpass.refresh_status
          metadata: {}
          data: {}
        - delay:
            hours: 0
            minutes: 0
            seconds: 2
            milliseconds: 0
        - action: fordpass.poll_api
          metadata: {}
          data: {}
description: >-
  Manually update FordPass data by running the sequence twice in case the first
  attempt fails.
mode: single
```


```
alias: Ford F-150 Morning Auto Start
description: Starts Ford F-150 in the morning based on temperature and kitchen presence
triggers:
  - trigger: time
    at: "07:40:00"
conditions:
  - condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: weather.forecast_home
            attribute: temperature
            below: 45
          - condition: numeric_state
            entity_id: weather.forecast_home
            attribute: temperature
            above: 85
      - condition: state
        entity_id: binary_sensor.kitchen_presence_sensor_occupancy
        state: "on"
actions:
  - action: script.update_fordpass
    data: {}
    continue_on_error: true
  - delay:
      seconds: 7
  - action: lock.lock
    target:
      entity_id: lock.fordpass_doorlock
    data: {}
  - delay:
      seconds: 1
  - action: switch.turn_on
    target:
      entity_id: switch.truck_ignition
    data: {}
mode: single
```


<img width="944" alt="Image" src="https://github.com/user-attachments/assets/57d08747-0c46-4d35-93e8-548fca7be1ef" />
