### ISSUE TITLE
Support for Electric Cars

### ISSUE THREAD

**Issue by warren1201** [itchannel/fordpass-ha#89]
Would be great to add support for the electric cars such as charge status and battery level

**Comment by itchannel** [comment]
I've added some basic values using data supplied from a hybrid. I'll see what I can add electric wise as long as the values are supported by the Ford API

**Comment by TerrorSource** [comment]
https://www.ford.no/owners/vehicle-dashboard
F12 in chrome
Search "status?country=nor&vin=%VIN%"

Full link = https://www.digitalservices.ford.com/owner/api/v2/ota/status?country=nor&vin=%VIN%
%VIN% = your VIN

vehiclestatus.batteryFillLevel
{
  "value": 91.5,
  "status": "LAST_KNOWN",
  "timestamp": "04/15/2021 09:52:56",
  "quarterRange": "FULL"
}

**Comment by Gruzzen** [comment]
I would second the request for the Mustang Mach-E charging status and battery level to be added into this integration if possible.

**Comment by TerrorSource** [comment]
@itchannel If you need something, let me know. Got a Mach-E at hand.

**Comment by itchannel** [comment]
If someone could add the following line to the sensor.py file for the integration on their installation "custom_components/fordpass/sensor.py" on Line 20 so it looks like the below:

```
_LOGGER.debug(sensor.coordinator.data)
```

```
async def async_setup_entry(hass, config_entry, async_add_entities):
    """Add the Entities from the config."""
    entry = hass.data[DOMAIN][config_entry.entry_id]

    for key, value in SENSORS.items():
        sensor = CarSensor(entry, key, config_entry.options)
        # Add support for only adding compatible sensors for the given vehicle
        _LOGGER.debug(sensor.coordinator.data)
        if key == "zoneLighting":
            if "zoneLighting" in sensor.coordinator.data:
                async_add_entities([sensor], True)
        elif key == "elVeh":
            if sensor.coordinator.data["elVehDTE"] != None:
                async_add_entities([sensor], True)
        else:
            async_add_entities([sensor], True)
```

Then add 
```
logger:
  logs:
    custom_components.fordpass: debug
``` 
to your configuration file. 

This will then log all data being retrieved from the fordpass API for your vehicle. If you could send me the log/vehicle status array minus any personal details I can see what a Mach-E response looks like and add the relevant functionality 👍 

Any problems drop me a line but quicker for someone to add this code than create a debug stream.

**Comment by itchannel** [comment]
Can you also check the elVeh sensor and see if it has the values you need as 1.17 did add some extra eletric vehicle values.

**Comment by TerrorSource** [comment]
@itchannel i've added the logger rule and restarted HA. how can i extract the logs you need?

If you want, you can do a remote session to check it for yourself. just send me a PM.

**Comment by itchannel** [comment]
@TerrorSource Can you check under the "ELVeh" sensor as I did add batteryfilllevel and a few other electric vehicle attributes to that sensor that might have what you want

**Comment by TerrorSource** [comment]
> @TerrorSource Can you check under the "ELVeh" sensor as I did add batteryfilllevel and a few other electric vehicle attributes to that sensor that might have what you want
> 
> Also if you added the debug you should now see a massive array of ford data in your logs, if you could send me that json array minus any personal details I can extract the relevant EV details that might be missing. Easiest way is just to search for fordpass in the log.

i really got no clue at all how you want me to get that logs.. i'm not an expert in HA or in extracting logs.

**Comment by wietseschmitt** [comment]
Hope this helps! ( Mustang Mach E )
`{
  "vehiclestatus": {
    "vin": "<REMOVED>",
    "lockStatus": {
      "value": "LOCKED",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "alarm": {
      "value": "NOTSET",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "PrmtAlarmEvent": {
      "value": "NULL",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "odometer": {
      "value": 908.0,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "fuel": null,
    "gps": {
      "latitude": "<REMOVED>",
      "longitude": "<REMOVED>",
      "gpsState": "UNSHIFTED",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "remoteStart": {
      "remoteStartDuration": 0,
      "remoteStartTime": 0,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "remoteStartStatus": {
      "value": 0,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "battery": {
      "batteryHealth": {
        "value": "STATUS_GOOD",
        "timestamp": "07-06-2021 07:06:54"
      },
      "batteryStatusActual": {
        "value": 15,
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      }
    },
    "oil": {
      "oilLife": "STATUS_GOOD",
      "oilLifeActual": 100,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "tirePressure": {
      "value": "STATUS_GOOD",
      "timestamp": "07-06-2021 07:06:54"
    },
    "authorization": "AUTHORIZED",
    "TPMS": {
      "tirePressureByLocation": {
        "value": 1,
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "tirePressureSystemStatus": {
        "value": "Systm_Activ_Composite_Stat",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "dualRearWheel": {
        "value": 1,
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "leftFrontTireStatus": {
        "value": "Normal",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "leftFrontTirePressure": {
        "value": "249",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "rightFrontTireStatus": {
        "value": "Normal",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "rightFrontTirePressure": {
        "value": "254",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "outerLeftRearTireStatus": {
        "value": "Normal",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "outerLeftRearTirePressure": {
        "value": "285",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "outerRightRearTireStatus": {
        "value": "Normal",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "outerRightRearTirePressure": {
        "value": "285",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "innerLeftRearTireStatus": {
        "value": "Not_Supported",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "innerLeftRearTirePressure": {
        "value": "65535",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "innerRightRearTireStatus": {
        "value": "Not_Supported",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "innerRightRearTirePressure": {
        "value": "65535",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "recommendedFrontTirePressure": {
        "value": 36,
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "recommendedRearTirePressure": {
        "value": 49,
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      }
    },
    "firmwareUpgInProgress": {
      "value": false,
      "timestamp": "07-06-2021 06:17:58"
    },
    "deepSleepInProgress": {
      "value": false,
      "timestamp": "07-06-2021 06:17:58"
    },
    "ccsSettings": {
      "timestamp": "06-23-2021 19:18:24",
      "location": 1,
      "vehicleConnectivity": 1,
      "vehicleData": 1,
      "drivingCharacteristics": 1,
      "contacts": 0
    },
    "lastRefresh": "07-06-2021 07:06:54",
    "lastModifiedDate": "07-06-2021 07:06:56",
    "serverTime": "07-06-2021 08:33:55",
    "batteryFillLevel": {
      "value": 78.5,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "elVehDTE": {
      "value": 282.0,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "hybridModeStatus": {
      "value": "Auto Charge Deplete Mode",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "chargingStatus": {
      "value": "NotReady",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "plugStatus": {
      "value": 0,
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "chargeStartTime": {
      "value": "07-06-2021 09:06:00",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "chargeEndTime": {
      "value": "07-06-2021 13:01:00",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "preCondStatusDsply": {
      "value": "Not Scheduled",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "chargerPowertype": null,
    "batteryPerfStatus": {
      "value": "Ok no message displayed",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "outandAbout": {
      "value": "PwPckOffTqNotAvailable",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "batteryChargeStatus": {
      "value": "NoReportRequest",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "dcFastChargeData": {
      "fstChrgBulkTEst": {
        "value": "1",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "fstChrgCmpltTEst": {
        "value": "115",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      }
    },
    "windowPosition": {
      "driverWindowPosition": {
        "value": "Fully closed position",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:55"
      },
      "passWindowPosition": {
        "value": "Fully closed position",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:55"
      },
      "rearDriverWindowPos": {
        "value": "Fully closed position",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:55"
      },
      "rearPassWindowPos": {
        "value": "Fully closed position",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:55"
      }
    },
    "doorStatus": {
      "rightRearDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "leftRearDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "driverDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "passengerDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "hoodDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "tailgateDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      },
      "innerTailgateDoor": {
        "value": "Closed",
        "status": "CURRENT",
        "timestamp": "07-06-2021 07:06:56"
      }
    },
    "ignitionStatus": {
      "value": "Off",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "batteryTracLowChargeThreshold": {
      "value": "Thres80km50mi",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "battTracLoSocDDsply": {
      "value": "Null",
      "status": "CURRENT",
      "timestamp": "07-06-2021 07:06:56"
    },
    "dieselSystemStatus": null
  },
  "version": "4.0.0",
  "status": 200
}`

**Comment by itchannel** [comment]
@wietseschmitt very helpful thank you

**Comment by stephywephy88** [comment]
It looks like this does support electric vehicles already, but for some reason I don't get any status changes or functionality even after using refresh. I do also get an error message re: fuellevel (I have no fuel). Could this be related to functionality? I deleted and reinstalled as well. Thank you!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 425, in _stringify_state
    state = self.state
  File "/config/custom_components/fordpass/sensor.py", line 362, in state
    return self.get_value("state")
  File "/config/custom_components/fordpass/sensor.py", line 53, in get_value
    return round(self.coordinator.data[self.sensor]["fuelLevel"])

**Comment by itchannel** [comment]
@stephywephy88 The pull request has now been merged so should resolve that error.

**Comment by smazurov** [comment]
I get SOC in my MachE with no issues using latest code, I think this issue can be closed.
