### ISSUE TITLE
[Feature Request] Guard mode

### ISSUE THREAD

**Issue by NickAx1** [itchannel/fordpass-ha#96]
Recently took ownership of my new ford vehicle and the fordpass app gives me an option to toggle guard mode. When guard mode is activated and I open a door I get an immediate notification on my phone. Is it possible to integrate this with HA both for guard mode alerts and turning on/off guard mode?

**Comment by itchannel** [comment]
Interesting new function. I'll try and look into it, just checked and my truck doesn't support it yet so may need someone to do some debugging who has "guard" mode so I can work out the API calls for it.

**Comment by itchannel** [comment]
Ok I've made some progress, I now have the relevant API calls to enable/disable and check guard status 

```
PUT api.mps.ford.com/api/guardmode/v1/MPBUMFF60LX299471/session (Enable Guard Mode)
GET api.mps.ford.com/api/guardmode/v1/MPBUMFF60LX299471/session (Get Guard Status)
DELETE api.mps.ford.com/api/guardmode/v1/MPBUMFF60LX299471/session (Disable Guard Mode)

I get "Enrollment in progress" so it isn't currently avaliable for my car. But if anyone wants to do me a favour I can give a python script to run to get the output for their car for me to test :)

**Comment by itchannel** [comment]
Ok I've made some progress, I now have the relevant API calls to enable/disable and check guard status 

```
PUT api.mps.ford.com/api/guardmode/v1/{VIN}/session (Enable Guard Mode)
GET api.mps.ford.com/api/guardmode/v1/{VIN}/session (Get Guard Status)
DELETE api.mps.ford.com/api/guardmode/v1/{VIN}/session (Disable Guard Mode)
```
I get "Enrollment in progress" so it isn't currently avaliable for my car. But if anyone wants to do me a favour I can give a python script to run to get the output for their car for me to test :)

**Comment by NickAx1** [comment]
I will be happy to test it out, might need some pointers as to what to do to get the output though.

**Comment by itchannel** [comment]
Cool. I'll edit the python debug script this weekend for you to run which will simply give you a log file to send with the required data.

**Comment by itchannel** [comment]
Took longer than planned but Guard functions are now in the test file if anyone is free to test. You will need to run the file in the "Guard Mode Branch" on the following repo [Guard Mode Debug](https://github.com/itchannel/ford_debug/tree/guard_mode)

Simply run the debug.py script specifying the parameters in the readme file. It will then spit out a log.txt with the values from the guard mode calls. To test enabling/disabling guard mode please uncomment the functions in debug.py.

Unfortunately for my truck I only get 
``` {"returnCode":300,"returnMessage":"Enrollment is still in progress.","session":null} ```

So unable to test on mine :(

**Comment by NickAx1** [comment]
hi, sorry its taken so long to test your script out but I'm pleased to say it works!

`{"returnCode":200,"returnMessage":"The request was Successful","session":{"lastModifiedDate":"2021-05-16T17:32:31.355Z","gmSessionId":181813,"gmStatus":"enable"}}`

Enabling/disabling also works. I need to force close the fordpass app on my phone for it to reflect the change but that's a ford issue and not a problem.

**Comment by itchannel** [comment]
Cool. I'll look at getting that implemented then when I have 5

**Comment by itchannel** [comment]
@NickAx1 I've now added guard mode into #104 however I've been unable to test so would be grateful if you could try it when you have 5.

**Comment by NickAx1** [comment]
I've done the update but I dont see the switch showing up in the list of sensors/switches in the HA component. Dont see it as a service call either so I am assuming this is an error.

**Comment by itchannel** [comment]
@NickAx1 Can you enable debug mode for the fordpass integration and look for this line in your log "Guard mode not supported on this vehicle". I'm wondering if the check is failing as I had to guess it slightly.

**Comment by denperss** [comment]
> @NickAx1 I've now added guard mode into #104 however I've been unable to test so would be grateful if you could try it when you have 5.

I can do some testing on it as well :) 
Nice update to see :) !

**Comment by serlinGi** [comment]
hello,
in my car the Guard mode is supported [perhaps :) ! ]
 this is the error in my log after updates:

_Logger: homeassistant.components.switch
Source: custom_components/fordpass/switch.py:21
Integration: Switch (documentation, issues)
First occurred: 11:31:52 PM (2 occurrences)
Last logged: 11:31:52 PM

Error while setting up fordpass platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fordpass/switch.py", line 21, in async_setup_entry
    if sw.coordinator.data["guardstatus"]["returnCode"] == 200:
  File "/usr/local/lib/python3.8/site-packages/dotted/collection.py", line 266, in __getitem__
    return self.store[key]
KeyError: 'guardstatus'_

I hope it will be useful to you or, if you want, please suggest me what tests I could do to help the cause

Thanks for all

**Comment by denperss11** [comment]
im getting this aswell'. 

Logger: homeassistant.components.switch
Source: custom_components/fordpass/switch.py:21
Integration: Switch (documentation, issues)
First occurred: 4:58:42 PM (1 occurrences)
Last logged: 4:58:42 PM

Error while setting up fordpass platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fordpass/switch.py", line 21, in async_setup_entry
    if sw.coordinator.data["guardstatus"]["returnCode"] == 200:
  File "/usr/local/lib/python3.8/site-packages/dotted/collection.py", line 266, in __getitem__
    return self.store[key]
KeyError: 'guardstatus'

**Comment by itchannel** [comment]
Can you please try #107 it should resolve the "Guard Status" error. It would also be good to get feedback on if people with guard mode now get the switch added or if they get a "Guard mode not supported on this vehicle" 👍

**Comment by NickAx1** [comment]
The latest update now shows the switch to toggle guard on/off but when I did nothing would happen and it would revert back to showing "on". I've also had a message from Ford in the app about "SecuriAlert" which looks like a rebranded guard mode. I've gone back and tested the debug script and that no longer works which makes me think they changed the API with this rebrand. I can't find what it may have changed to though but if somebody knows what it is now I can test it.

**Comment by itchannel** [comment]
@NickAx1 ok will take a look again. 

If you have time to test could you enable debug mode for fordpass as it will then output the results from the Guard mode switch so I can see what response your now getting. 
```
logger:
  logs:
    custom_components.fordpass: debug
```

**Comment by serlinGi** [comment]
hello,
I confirm that the switch-button always return to the ON position;
I tested simultaneously with FordPass app and in debug mode; this is the log result with my commented action

''#
#' with securityAlert not active in app:
2021-06-26 08:51:49 DEBUG (SyncWorker_10) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:51:49 DEBUG (SyncWorker_10) [custom_components.fordpass.fordpass_new] {"returnCode":303,"returnMessage":"No active session found"}
2021-06-26 08:51:49 DEBUG (SyncWorker_24) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:51:50 DEBUG (SyncWorker_15) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:51:51 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.261 seconds
2021-06-26 08:51:51 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-26T06:51:51.124Z', 'gmSessionId': 366034, 'gmStatus': 'disable'}}
# no result in app
#
#
# with SecurityAlert activate in app:
2021-06-26 08:55:30 DEBUG (SyncWorker_9) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:55:31 DEBUG (SyncWorker_9) [custom_components.fordpass.fordpass_new] {"returnCode":200,"returnMessage":"The request was Successful"}
2021-06-26 08:55:31 DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:55:31 DEBUG (SyncWorker_28) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 08:55:32 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.312 seconds
2021-06-26 08:55:32 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-26T06:55:32.450Z', 'gmSessionId': 366059, 'gmStatus': 'disable'}}
# the SecurityAlarm has been turned in FordPass App
#''

I am doing these tests after completely eliminating and reinstalling your integration by adding only one car: after the last update, with 2 cars, my main one was constantly in unavailble state and so I thought about starting over.

up to now everything runs perfectly (except the switch back)  even if I have not yet checked the update times of the various sensors which, before uninstalling, had become long and unreliable.

forgive my not perfect english result (also) of google translate help.

;)

**Comment by NickAx1** [comment]
`2021-06-26 09:34:15 DEBUG (SyncWorker_8) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 09:34:15 DEBUG (SyncWorker_8) [custom_components.fordpass.fordpass_new] {"returnCode":200,"returnMessage":"The request was Successful"}
2021-06-26 09:34:15 DEBUG (SyncWorker_15) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 09:34:16 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-26 09:34:16 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 0.929 seconds
2021-06-26 09:34:16 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-26T08:34:16.685Z', 'gmSessionId': 361316, 'gmStatus': 'disable'}}`

The output of my logs when toggling guard mode. Same message as using the test debug script

**Comment by itchannel** [comment]
#108 Should fix the guard mode status reporting incorrectly. 

However I have noticed the fordpass API has started reporting a 200 OK message for the guard mode endpoint so may need to revise the check I use for only adding the guard mode entity when a persons car supports it. 

If you could check your instances now and see it it reports correctly that would be helpful 👍

**Comment by NickAx1** [comment]
Sadly it doesnt work but the same response in the debug window

`2021-07-01 22:28:51 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.099 seconds
2021-07-01 22:28:51 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-07-01T21:28:51.351Z', 'gmSessionId': 426933, 'gmStatus': 'disable'}}`

**Comment by itchannel** [comment]
@NickAx1 How about the switch itself, is that now reporting the correct status?

**Comment by NickAx1** [comment]
The switch now stays in the off position. Turning it on results in it turning back off after a couple of seconds.

**Comment by serlinGi** [comment]
and the guard mode is activated regularly if it is in the deactivated state;  on the other hand, if it is already active, the toggle has no effect.

**Comment by itchannel** [comment]
Oh interesting. I need to look into the API changes more as it seems guard mode has been changed slightly in the latest app version.

**Comment by canuckcam** [comment]
Guard mode was deactivated/greyed out from v1.29? It worked for a while for me and I got notifications on my app, but recently it stopped so wanted to try to toggle it on the plugin again. Thanks!
