### ISSUE TITLE
Lockstatus

### ISSUE THREAD

**Issue by root01** [itchannel/fordpass-ha#99]
Is there a Problem with the Lockstatus? In the past i make i refresh of status an it works fine. One or two weeks ago, refresh doesn't work. The locked car is still "unlocked" (in the pass pro app to). It need a lock with the app an then its locked in the app an api. Can someone test this? Thanks.

**Comment by itchannel** [comment]
I've never had it report "locked" without polling the car first running the "refresh_status" it only ever auto updates the "Unlocked" status. However I can report that it is still working for me on my automation which polls the car 15mins after I arrive home to get the latest car status which is the way I'd recommend doing it.

**Comment by root01** [comment]
I think there is a problem with my HASS:
`[139651044093376] Error handling message: Unknown error
16:22:29 – (FEHLER) Home Assistant WebSocket API
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Expecting value: line 1 column 1 (char 0)
16:22:29 – (FEHLER) custom_components/fordpass/fordpass_new.py
`

**Comment by root01** [comment]
I do a complete new HASS installation and the Problem is the same.

`2021-04-16 19:58:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-16 19:58:36 WARNING (MainThread) [homeassistant.loader] You are using a custom integration fordpass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-16 19:58:42 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-04-16 19:58:42 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-04-16 19:58:42 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2021-04-16 20:04:24 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/fordpass/__init__.py", line 68, in async_refresh_status_service
await hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fordpass/__init__.py", line 99, in refresh_status
coordinator.vehicle.requestUpdate()
File "/config/custom_components/fordpass/fordpass_new.py", line 241, in requestUpdate
return status.json()["status"]
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-16 20:04:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140456402290720] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
await script_obj.async_run(context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/fordpass/__init__.py", line 68, in async_refresh_status_service
await hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fordpass/__init__.py", line 99, in refresh_status
coordinator.vehicle.requestUpdate()
File "/config/custom_components/fordpass/fordpass_new.py", line 241, in requestUpdate
return status.json()["status"]
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

need help please

**Comment by itchannel** [comment]
@root01 sorry for the delay. It looks like there's something going on with the value your getting back for the status array. You said it used to work ok for you? Is your fordpass app still working ok?

If you have 5mins if you could run the following python script and send me the contents of the log file I can look and see what data is being sent that is causing the error. 

[Debug Script](https://github.com/itchannel/ford_debug)

**Comment by root01** [comment]
i get: 
```
File "debug.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by itchannel** [comment]
Can I confirm you are running python3 and not python2?

**Comment by root01** [comment]
python3 --version
Python 3.5.3

**Comment by JuhaFIN1** [comment]
Here is same problem, i lock doors with key and walk home, home assistant show doors unlocked... i walk to car, doors are locked!

**Comment by itchannel** [comment]
@JuhaFIN1 Do you run the refresh car service? As by default ford's API only updates on unlock but not lock. So you need to run the service I created to poll the car for it's latest data. This is a manual process to avoid automated polling and draining of the cars battery.

Generally I do this when HA detects that I'm home, So if Person1 = home, run fordpass.refresh_status_

**Comment by JuhaFIN1** [comment]
> @JuhaFIN1 Do you run the refresh car service? As by default ford's API only updates on unlock but not lock. So you need to run the service I created to poll the car for it's latest data. This is a manual process to avoid automated polling and draining of the cars battery.
> 
> Generally I do this when HA detects that I'm home, So if Person1 = home, run fordpass.refresh_status_

I dont know what is this "refresh car service? How and where? :)

Please tell me more!

**Comment by itchannel** [comment]
In HA if you look under services you will see a service called "fordpass.refresh_status" if you run this it will poll all cars added and get the latest status from the car. 

You can then use it in an automation to automatically get the status of the car for example when you arrive home. An example of my config is shown below

```
- alias: "Update Car"
  trigger:
    - platform: state
      entity_id: person.steve
      to: home
  action:
    - delay: 00:15:00
    - service: fordpass.refresh_status
  ```

**Comment by JuhaFIN1** [comment]
> In HA if you look under services you will see a service called "fordpass.refresh_status" if you run this it will poll all cars added and get the latest status from the car.
> 
> You can then use it in an automation to automatically get the status of the car for example when you arrive home. An example of my config is shown below
> 
> ```
> - alias: "Update Car"
>   trigger:
>     - platform: state
>       entity_id: person.steve
>       to: home
>   action:
>     - delay: 00:15:00
>     - service: fordpass.refresh_status
> ```
> 
> By doing it this way it doesn't unnecessarily poll the car to drain battery but ensures you always have the latest data accessible to you.

Thank you very much this helpful detailed instructions ! :) But this logic works only if at home or some else Zones. And we use IOS app, so that dosent change status to home until i open app. And think this scenario: I drive to some random Shopping Center and lock car in parking lot, go shopping, eat and maybe to Cinema. Then i want to see status off locks -> unlocked.
Is there another way to automatically check lock status? And i understand this if make automatically use this refresh status, it can run out off battery in car.

**Comment by itchannel** [comment]
It's a service so you can call it with any automation you like. If battery discharge isn't something you worry about then just have HA run an automation that refreshes the status every X amount of time. Unfortunately the fordpass API/service doesn't update itself on locking so this is the only way to do it.

**Comment by root01** [comment]
I have still the same issues with the "fordpass.refresh_status" service. Anything else works like a charm.

https://github.com/itchannel/fordpass-ha/issues/99#issuecomment-819559008

**Comment by itchannel** [comment]
@root01 It looks like the response from the fordpass API is not containing the expected data from your car. Best option to debug is for me to add some extra debugging for that function and get you to a custom git branch so we can debug it. 

I'll try and sort out some code for you to debug later today.

**Comment by root01** [comment]
That sounds great!

**Comment by itchannel** [comment]
Ok if you use the root_debug_branch I have added some code to log the response and status code to the HA log when running the "refresh_status" service. 

You can either clone that branch and run it on your HA or manually edit the fordpass_new.py file and change the "requestUpdate" function to look like below:
```
    def requestUpdate(self, vin=""):
        # Send request to refresh data from the cars module
        self.__acquireToken()
        if vin:
            vinnum = vin
        else:
            vinnum = self.vin
        status = self.__makeRequest(
            "PUT", f"{baseUrl}/vehicles/v2/{vinnum}/status", None, None
        )
        _LOGGER.debug(status.text)
        _LOGGER.debug(status.status_code)
        return status.json()["status"]
```

Finally you will need to enable debug mode for the fordpass integration by adding the below to your main configuration file:
```
logger:
  logs:
    custom_components.fordpass: debug
```

**Comment by root01** [comment]
Thanks. Got it. Next step?

**Comment by itchannel** [comment]
Run the refresh service and then send me the log output from your HA instance. Only need the fordpass relevant items. 

Make sure you restart first to apply the changes!

**Comment by root01** [comment]
How can i separate the ford pass logs ? the point is Setup->Logs right? There i have only "complete HA log"

**Comment by itchannel** [comment]
Unfortunately no easy way. I recommend restarting HA then running the fordpass service before the log gets too big. Then just picking out the relevant fordpass log entries. Or just copy and paste the log into a textfile and the grep for "custom_components.fordpass"

**Comment by root01** [comment]
`2021-06-24 10:23:47 DEBUG (MainThread) [custom_components.fordpass] vin
2021-06-24 10:23:47 DEBUG (MainThread) [custom_components.fordpass] username
2021-06-24 10:23:47 DEBUG (MainThread) [custom_components.fordpass] region
2021-06-24 10:23:47 DEBUG (MainThread) [custom_components.fordpass] password
2021-06-24 10:23:47 DEBUG (MainThread) [custom_components.fordpass] UK&Europe
2021-06-24 10:23:50 DEBUG (SyncWorker_5) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 10:23:52 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 4.259 seconds
2021-06-24 10:23:52 DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 10:23:52 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-24T08:23:52.080Z', 'gmSessionId': 138664, 'gmStatus': 'enable'}}
2021-06-24 10:23:53 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 10:23:53 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 1.361 seconds
2021-06-24 10:23:53 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-24T08:23:53.639Z', 'gmSessionId': 138664, 'gmStatus': 'enable'}}
2021-06-24 10:24:01 DEBUG (SyncWorker_6) [custom_components.fordpass] Running Service
2021-06-24 10:24:01 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2`

**Comment by itchannel** [comment]
So I can't see that the service has returned yet in that log. There should be some more output after the "Running Service" entry. I'm also guessing your car supports guard mode 👍

**Comment by root01** [comment]
no its not. I think there is a problem with the service itself, it don't run. I get an "unknown error" on the left bottomsite when i running the refresh service.

**Comment by root01** [comment]
i get an python error. Can this be the problem?
Logger: aiohue.util
Source: /usr/local/lib/python3.8/site-packages/aiohue/util.py:21

Is a brand new HA installation, only HACS, Fileeditor, SSH Terminal and Fordpass is installed

**Comment by itchannel** [comment]
Yep thats part of the built in Hue integration. 

It looks like your HA does at least trigger the update function but doesn't perform the request to the API. If you can add the below code we can look in the log to see exactly what is being sent on your instance. I can't unfortunately edit the branch right now as I'm not at my dev pc so will have to wait for tomorrow if you can't do the below.

Are you comfortable with adding the following code to the fordpass_new.py file. 

Before Line 298 add 
```
_LOGGER.debug("running status check")
```

Above the two debug messages on Line 301 add

```
_LOGGER.debug(status.request.headers)
_LOGGER.debug(status.request.URL)
_LOGGER.debug(status.request.data)
```

**Comment by root01** [comment]
`2021-06-24 14:37:27 DEBUG (MainThread) [custom_components.fordpass] vin
2021-06-24 14:37:27 DEBUG (MainThread) [custom_components.fordpass] username
2021-06-24 14:37:27 DEBUG (MainThread) [custom_components.fordpass] password
2021-06-24 14:37:27 DEBUG (MainThread) [custom_components.fordpass] region
2021-06-24 14:37:27 DEBUG (MainThread) [custom_components.fordpass] UK&Europe
2021-06-24 14:37:27 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] No token, or has expired, requesting new token
2021-06-24 14:37:30 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] {'httpStatus': 0, 'status': 200, 'requestStatus': None, 'error': None, 'lastRequested': None, 'version': None, 'UserProfile': None, 'access_token': 'eyJ0eXAiOiJKV1QiLCJ0b2tlbl90eXBlIjoiQSIsImFsZyI6IlJTMjU2Iiwia2lkIjoiY3NkbmtleTEifQ.eyJzdWIiOiIwMGVkMDJiMy0yYzQxLTQyYjktOTEwMS05MWY5NjdmMmZiMTMiLCJhdWQiOiIxZThjNzc5NC1mZjVmLTQ5YmMtOTU5Ni1hMWUwYzg2YzViMTkiLCJpc3MiOiJENzY4MDFGQS01MjA1LTQ3RTctQUI2QS1EMEY1NDA4QUIxRkEiLCJ0eXBlIjoic3NvIiwiZXhwIjoxNjI0NTQwMDQ5LCJpYXQiOjE2MjQ1MzgyNDksImp0aSI6IjAwZWQwMmIzLTJjNDEtNDJiOS05MTAxLTkxZjk2N2YyZmIxM3wxNjI0NTM4MjQ5OTU4fGEiLCJ1c2VybmFtZSI6InJlbmVAc2l0dGVybGVlLmNvbSJ9.lleryNc8GJyB8tLlk_L0XvEr9nLX8j0HWp46etbxOvtnVwEQMhIhaUhyff2wzoQjDDcTVkXhMPunF1dzXO_2f4jE0JC7OKVrExCRdVZB-u1xFN2BUL95Qih3jSlexroMOrflZkRbJj-oy1YLwegx3lRWdYQ1ZkkWe_MwVMzfIJQleZq2XAjyENaL0ILWbbdueq_FWlos1QGmGgb3p0gnYuqPtl00C4JU_wEfcf0cC_ZHXMwWJSI-11lumH0pG5PnOtfkP9ByGrkN1KbaqGuql0QV2bmL7vW9YPyCCr_ow297Ld-KhnItDBFSH7IOH6DLuFh7G2dujnZkYN4R62_0Cg', 'refresh_token': 'eyJ0eXAiOiJKV1QiLCJ0b2tlbl90eXBlIjoiUiIsImFsZyI6IlJTMjU2Iiwia2lkIjoiY3NkbmtleTEifQ.eyJzdWIiOiIwMGVkMDJiMy0yYzQxLTQyYjktOTEwMS05MWY5NjdmMmZiMTMiLCJhdWQiOiIxZThjNzc5NC1mZjVmLTQ5YmMtOTU5Ni1hMWUwYzg2YzViMTkiLCJkZXZpY2VfaWQiOm51bGwsImlzcyI6IkQ3NjgwMUZBLTUyMDUtNDdFNy1BQjZBLUQwRjU0MDhBQjFGQSIsInR5cGUiOiJzc28iLCJleHAiOjE2NTYwNzA1OTQsImlhdCI6MTYyNDUzNDU5NCwianRpIjoiMDBlZDAyYjMtMmM0MS00MmI5LTkxMDEtOTFmOTY3ZjJmYjEzfDE2MjQ1MzQ1OTQyMjQiLCJ1c2VybmFtZSI6InJlbmVAc2l0dGVybGVlLmNvbSJ9.D34GOtp3-MOilmubU23GXVQIaK6BZgm_p6BLvJP1a3fx-TZV7pAo3KG-IX81FvVHnvhumCp7HaCXrwRUohmREocL9u9aX69RkEqT7JHhR5QfX7Aor8lOfo_GqL4SLI5rLoCR8Ves8ApewTSVuUFms7ltAf2206RUz_RTsNH0rjVeMfrtFBaeKnFIKz-d9xvh-szbeSNzorPU01e-sIp6pqDz8aYoZ6w5BJXDq4kdSfpWuSLWsIs5rgEG80KXdE_GKihYmG3ryRpSe_O8GPlTg3bjUlPpeMhIJtc_l_PClhd5o3u_Eyc7YmSy58SjHbdUv3oFLLKbl71otbM4-Kbo_g', 'cat1_token': 'eyJ0eXAiOiJKV1QiLCJ0b2tlbl90eXBlIjoiQSIsImFsZyI6IlJTMjU2Iiwia2lkIjoiY3NkbmtleTEifQ.eyJzdWIiOiIwMGVkMDJiMy0yYzQxLTQyYjktOTEwMS05MWY5NjdmMmZiMTMiLCJhdWQiOiIxZThjNzc5NC1mZjVmLTQ5YmMtOTU5Ni1hMWUwYzg2YzViMTkiLCJpc3MiOiJENzY4MDFGQS01MjA1LTQ3RTctQUI2QS1EMEY1NDA4QUIxRkEiLCJ0eXBlIjoic3NvIiwiZXhwIjoxNjI0NTQwMDQ5LCJpYXQiOjE2MjQ1MzgyNDksImp0aSI6IjAwZWQwMmIzLTJjNDEtNDJiOS05MTAxLTkxZjk2N2YyZmIxM3wxNjI0NTM4MjQ5OTU4fGEiLCJ1c2VybmFtZSI6InJlbmVAc2l0dGVybGVlLmNvbSJ9.lleryNc8GJyB8tLlk_L0XvEr9nLX8j0HWp46etbxOvtnVwEQMhIhaUhyff2wzoQjDDcTVkXhMPunF1dzXO_2f4jE0JC7OKVrExCRdVZB-u1xFN2BUL95Qih3jSlexroMOrflZkRbJj-oy1YLwegx3lRWdYQ1ZkkWe_MwVMzfIJQleZq2XAjyENaL0ILWbbdueq_FWlos1QGmGgb3p0gnYuqPtl00C4JU_wEfcf0cC_ZHXMwWJSI-11lumH0pG5PnOtfkP9ByGrkN1KbaqGuql0QV2bmL7vW9YPyCCr_ow297Ld-KhnItDBFSH7IOH6DLuFh7G2dujnZkYN4R62_0Cg', 'userId': '00ed02b3-2c41-42b9-9101-91f967f2fb13', 'expires_in': 1800, 'refresh_expires_in': 31556952, 'expiry_date': 1624540050.0613203}
2021-06-24 14:37:30 DEBUG (SyncWorker_3) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 14:37:31 DEBUG (SyncWorker_2) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 14:37:33 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 5.370 seconds
2021-06-24 14:37:33 DEBUG (SyncWorker_5) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 14:37:33 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-24T12:37:32.541Z', 'gmSessionId': 138664, 'gmStatus': 'enable'}}
2021-06-24 14:37:34 DEBUG (SyncWorker_0) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 14:37:36 DEBUG (MainThread) [custom_components.fordpass] Finished fetching fordpass data in 2.622 seconds
2021-06-24 14:37:36 DEBUG (MainThread) [custom_components.fordpass.switch] {'returnCode': 200, 'returnMessage': 'The request was Successful', 'session': {'lastModifiedDate': '2021-06-24T12:37:36.062Z', 'gmSessionId': 138664, 'gmStatus': 'enable'}}
2021-06-24 14:39:58 DEBUG (SyncWorker_6) [custom_components.fordpass] Running Service
2021-06-24 14:39:58 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] Token is valid, continuing
2021-06-24 14:39:58 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] running status check
2021-06-24 14:40:00 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new]
2021-06-24 14:40:00 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] 429
2021-06-24 14:40:00 DEBUG (SyncWorker_6) [custom_components.fordpass.fordpass_new] {'User-Agent': 'fordpass-ap/93 CFNetwork/1197 Darwin/20.0.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Accept-Language': 'en-us', 'Content-Type': 'application/json', 'auth-token': 'eyJ0eXAiOiJKV1QiLCJ0b2tlbl90eXBlIjoiQSIsImFsZyI6IlJTMjU2Iiwia2lkIjoiY3NkbmtleTEifQ.eyJzdWIiOiIwMGVkMDJiMy0yYzQxLTQyYjktOTEwMS05MWY5NjdmMmZiMTMiLCJhdWQiOiIxZThjNzc5NC1mZjVmLTQ5YmMtOTU5Ni1hMWUwYzg2YzViMTkiLCJpc3MiOiJENzY4MDFGQS01MjA1LTQ3RTctQUI2QS1EMEY1NDA4QUIxRkEiLCJ0eXBlIjoic3NvIiwiZXhwIjoxNjI0NTQwMDQ5LCJpYXQiOjE2MjQ1MzgyNDksImp0aSI6IjAwZWQwMmIzLTJjNDEtNDJiOS05MTAxLTkxZjk2N2YyZmIxM3wxNjI0NTM4MjQ5OTU4fGEiLCJ1c2VybmFtZSI6InJlbmVAc2l0dGVybGVlLmNvbSJ9.lleryNc8GJyB8tLlk_L0XvEr9nLX8j0HWp46etbxOvtnVwEQMhIhaUhyff2wzoQjDDcTVkXhMPunF1dzXO_2f4jE0JC7OKVrExCRdVZB-u1xFN2BUL95Qih3jSlexroMOrflZkRbJj-oy1YLwegx3lRWdYQ1ZkkWe_MwVMzfIJQleZq2XAjyENaL0ILWbbdueq_FWlos1QGmGgb3p0gnYuqPtl00C4JU_wEfcf0cC_ZHXMwWJSI-11lumH0pG5PnOtfkP9ByGrkN1KbaqGuql0QV2bmL7vW9YPyCCr_ow297Ld-KhnItDBFSH7IOH6DLuFh7G2dujnZkYN4R62_0Cg', 'Application-Id': '1E8C7794-FF5F-49BC-9596-A1E0C86C5B19', 'Content-Length': '0'}
`

**Comment by itchannel** [comment]
You seem to be getting a 429 too many requests error from the API. I can't say I've ever seen it do that before. Any chance you could rerun it and send me the log again just incase that error was a one off and not the one you've been getting.

**Comment by root01** [comment]
I test it in Ford Pass app. I have 2 cars in the app and at this car with "HA" can't refresh with using the app and the other car without HA can refresh. I thing i do an Factory Reset of Sync3 and disconnect Ford Pass and then i test it again.

**Comment by itchannel** [comment]
Ok cool. Let me know the outcome 👍

**Comment by JuhaFIN1** [comment]
> Thanks. Got it. Next step?

Now it did it again, tank is 95% full and Ford Ios app dosent show fuel at all and ha shows -5
![7E5F847A-4157-4C07-819F-6476D732F66E](https://user-images.githubusercontent.com/70380474/124773324-86aaa580-df45-11eb-996e-bfd6883bb061.jpeg)
![93FA6F32-A929-4B14-B446-4DE73420BE0B](https://user-images.githubusercontent.com/70380474/124773328-88746900-df45-11eb-93e6-5bf0da9915ba.jpeg)

**Comment by itchannel** [comment]
Closing old issue for housekeeping
